export const LIST_ALL_LOCATION = "LIST_ALL_LOCATION";
export const POST_SELECTED_LOCATION = "POST_SELECTED_LOCATION";
export const GET_SELECTED_LOCATION = "GET_SELECTED_LOCATION";
export const ADD_DATA = "ADD_DATA";
